---
kind: Template
apiVersion: v1
metadata:
  name: authorization-build
  annotations:
    openshift.io/display-name: S2I App Build Template
    description: S2I binary build config to create an image with your app baked in.
    iconClass: fa-cube
    tags: s2i
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${NAME}"
    name: "${NAME}"
  spec:
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:{BUILD_TAG}"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${IMAGE_STREAM_TAG_NAME}
          namespace: ${IMAGE_STREAM_NAMESPACE}
        type: Source
  status:
    lastVersion: 1
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "${NAME}"
    name: "${NAME}"
  spec: {}
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: s2i-app
- name: BUILD_TAG
  displayName: Build Tag for Docker image
  description: The tag to apply to the Docker image being built.
  required: true
  value: latest
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Image stream tag for the image you'd like to use to build the application
  name: IMAGE_STREAM_TAG_NAME
  required: true
  value: redhat-openjdk18-openshift:1.4
labels:
  template: authorization-build-template
