---
kind: Template
apiVersion: v1
metadata:
  name: authorizationapp-deploy
  annotations:
    openshift.io/display-name: Static react js App Deploy Template
    description: A template to deploy your an App with a HTTP endpoint
    iconClass: icon-cube
    tags: http
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "${NAME}"
    name: "${NAME}"
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    replicas: 1
    selector:
      name: "${NAME}"
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp:
        labels:
          name: "${NAME}"
      spec:
        containers:
        - image: "docker-registry.default.svc:5000/${NAMESPACE}/${NAME}:${APP_TAG}"
          imagePullPolicy: Always
          name: "${NAME}"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          readinessProbe:
            httpGet:
              path: api/actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 120
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dsa"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:sqlserver://mssql:1433;databaseName=tiedb"
          - name: SPRING_DATASOURCE_USERNAME
            value: "${SPRING_DATASOURCE_USERNAME}"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "${SPRING_DATASOURCE_PASSWORD}"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: "${NAME}"
    name: "${NAME}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: "${NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: "${NAME}"
    name: "${NAME}"
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: "${NAME}"
      weight: 100
    wildcardPolicy: None
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the related imagestream.
  required: true
- name: APP_TAG
  displayName: App Tag
  description: The tag of the image to use eg latest.
  required: true
- name: NAMESPACE
  displayName: Docker image namespace
  description: The namespace of the image to use eg js-apps.
  required: true
- name: SPRING_DATASOURCE_USERNAME
  displayName: Username for MSSQL
  description: Environment specific username for MSSQL.
  required: true
- name: SPRING_DATASOURCE_PASSWORD
  displayName: Username for MSSQL
  description: Environment specific password for MSSQL.
  required: true
labels:
  template: authorizationapp-deploy-template
