spring:
  application:
    name: authorization
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    #url: jdbc:oracle:thin:@oracle-service:1521:xe
    #driverClassName: oracle.jdbc.OracleDriver
    #  url: jdbc:postgresql://localhost:5432/test
    #  driverClassName: org.postgresql.Driver
    username: TIE_MEGA_SCHEMA
    password: Pass1234
management:
  server:
    port: 8082
  endpoint:
    health:
      show-details: "WHEN_AUTHORIZED"
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown,health,info
server:
  port: 8080
  servlet:
    context-path: /auth
keystore:
  password: mySecretKey