spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    #url: jdbc:oracle:thin:@oracle-service:1521:xe
    #driverClassName: oracle.jdbc.OracleDriver
    #  url: jdbc:postgresql://localhost:5432/test
    #  driverClassName: org.postgresql.Driver
    username: TIE_MEGA_SCHEMA
    password: Pass1234
logging:
  config: classpath:log4j2-docker-localhost.xml
  level:
    org.springframework.security: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
