apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  labels:
    app: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
      - name: authorization
        image: tie-team/authorization:1.0-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  labels:
    app: authorization
spec:
  selector:
    app: authorization
  ports:
  - port: 8080