apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizationapp
  labels:
    app: authorizationapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorizationapp
  template:
    metadata:
      labels:
        app: authorizationapp
    spec:
      containers:
      - name: authorizationapp
        image: tie-team/authorizationapp:1.0-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  labels:
    app: authorizationapp
spec:
  selector:
    app: authorizationapp
  ports:
  - port: 8080